### ISSUE TITLE
Amazon SES mail transport

### ISSUE THREAD

**Issue by resurtm** [2amigos/mailer-library#6]
@tonydspaniard, what do you think about the idea of creating Amazon SES transport? Without Swift Mailer usage, and other layers. I mean it should use Amazon SES API directly (https://aws.amazon.com/ses/).

I think it should be, I prefer to use Amazon SES direct API where possible. I can work on this.

**Comment by tonydspaniard** [comment]
@resurtm Currently, SMTP transport has been added. That way the library is not attached to any of the services out there. Using SwiftMailer SMTP capabilities allow the user to use any SMTP configuration. Whats the benefit or using purely SES?
