### ISSUE TITLE
Yii2 adapter library/project

### ISSUE THREAD

**Issue by resurtm** [2amigos/mailer-library#7]
@tonydspaniard, what do you think about creating Yii2 adapter library/project?

It will be dead simple. Application component, and some other minor integration parts. I can work on this as well.

Also I can create such adapter for Yii1.1, even it's obsolete. ;-)

**Comment by tonydspaniard** [comment]
We should create that as a separated repositories on our [http://github.com/2amigos](http://github.com/2amigos) page. I am all up for it.

**Comment by resurtm** [comment]
@tonydspaniard, that's what I meant. Can you create it please? I'll start working on that. ;-)

**Comment by tonydspaniard** [comment]
Yes sir!
